node-jenkins-app-example:
  restart: always
  image: node-jenkins-app-example
  build: ./node-jenkins-app-example
  container_name: node-jenkins-app-example
  environment:
    - VIRTUAL_HOST=portainer.superwebserver.net
    - VIRTUAL_PORT=3000


# Option-1 : Createting docker image using command module 
#---
#- hosts: all
#  become: true
#  tasks:
#  - name: building docker image
#    command: docker build -t simple-devops-image .
#    args:
#      chdir: /home/dockeradmin

# option-2 : creating docker image using docker_image module 

#  tasks:
#  - name: building docker image
#    docker_image:
#      build:
#        path: /opt/docker
#      name: simple-devops-image
#     tag: v1
#     source: build